@startuml
allow_mixing

rectangle "Polar Bookshop \n [Software system]" #line.dashed {
    rectangle catalogService [
        **Catalog Service**
        [Container: Spring Boot]

        Provides functionality for managing the books in the catalog
    ]

    rectangle configService [
        **Config Service**
        [Container: Spring Boot]

        Provides centralized configuration
    ]

    database configRepo [
        **Config Repo**
        [Container: Git]

        Stores configuration data
    ]
}


catalogService .right> configService: Gets configuration from\n [REST/HTTP]
configService ..> configRepo: Reads configuration from\n [REST/HTTP]

@enduml